{"name": "test_get_title", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31mNone\napi-tests\\test_api_status.py:26 in test_get_title() -> with check.raises(AssertionError):\n\u001b[0m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31mNone\napi-tests\\test_api_status.py:26 in test_get_title() -> with check.raises(AssertionError):\n\u001b[0m\n------------------------------------------------------------\nFailed Checks: 1"}, "start": 1681896930590, "stop": 1681896931527, "uuid": "288a8f19-ae73-4e63-b6d2-8b8c1afc4ba3", "historyId": "247888500e3d698638b8ec1dd6210063", "testCaseId": "87c340832193f86c7f73fc9348d4034a", "fullName": "api-tests.test_api_status.TestOrfium#test_get_title", "labels": [{"name": "parentSuite", "value": "api-tests"}, {"name": "suite", "value": "test_api_status"}, {"name": "subSuite", "value": "TestOrfium"}, {"name": "host", "value": "N-20N3PF141YQ9"}, {"name": "thread", "value": "26628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api-tests.test_api_status"}]}